= Цель и задачи проекта

== Цель проекта

Изучить  и применить на практике унифицированный процесс разработки программного обеспечения на примере реализации приложения «Система обучения и тестирования учащихся лицея (СОТ)» 

== Задачи

[width="100%",frame="topbot",options="header"]
|=======
|Этап проектирования |Задачи этапа проектирования 
|Подготовительный этап |1.	Обзор и выбор методики разработки ПО

2.	Определение ролей участников проекта
|Анализ и Проектирование |1.	Определение функциональных требований

2.	Создание технического задания (ТЗ) на разработку СОТ

3.	Формирование календарного графика реализации проекта (RoadMap)

4.	Изучение основ унифицированного языка моделирования UML на примере создания диаграмм СОТ

5.	Разработка функциональной модели СОТ с использованием комплексного графического инструмента проектирования Enterprise Architect
|Реализация |1.	Определение минимального полезного функционала (MVP) по модели СОТ

2.	Реализация MVP СОТ
|Тестирование |1.	Изучение методов и проведение системного тестирование

2.	Изучение методов и проведение интеграционного тестирование

3.	Приемосдаточныее испытания
 
|=======


== Разъяснение задач этапов проектирования
=== подготовительного этапа
1. существует 2 метода разработки ПО: waterfall и agile

 waterfall(каскад,водопад) — метод проектирования при котором весь процесс является жестким и линейным, имеет четкие цели для каждого этапа, новая фаза начинается по завершению предыдущей, нет возврата назад. Преимущества — децентрализация и строгий контроль над сроками и качеством исполнения работы 
 На практике Waterfall часто не оправдывает ожиданий, поскольку игнорирует динамические изменения. Так, после тестирования очень сложно откатить процесс и заложить функции, не учтенные на стадии разработки.
 
 Agile — метод гибкой разработки программного обеспечения, предполагающий большое количество итераций(циклов), позволяющий без негативных последствий изменять направление деятельности, вносить дополнительные задания, требовать детальной проработки узких мест
 Несмотря на недостатки, Agile стала фундаментальной концепцией для разработки ПО и стала основной частью других методик
 
=== этапа анализа и проектирования
1. Роль в проекте (проектная роль) - определенный набор функций и полномочий в проекте, созданный с целью распределения обязанностей между членами команды проекта.

 Заказчик (product owner)- сторона, заинтересованная в осуществлении проекта и достижении его целей, будущий владелец результатов проекта. Заказчик определяет основные требования к результатам проекта, обеспечивает финансирование проекта за счет своих или привлекаемых средств, может заключать контракты с основными исполнителями проекта.
 
 Менеджер проекта - лицо, ответственное за управление проектом. Менеджер проекта несет ответственность за достижение целей проекта в рамках бюджета, в срок и с заданным уровнем качества.
 
 Контрактор (аналитики, разработчики, тестировщики) – сторона или участник проекта, вступающий в отношения с заказчиком, и берущий на себя ответственность за выполнение работ и услуг по контракту – это может быть весь проект или его часть.
 
 Потребители конечной продукции (пользователь) – юридические и физические лица, являющиеся покупателями и пользователями результата проекта, определяющие требования к производимой продукции и оказываемым услугам, формирующие спрос на них.
 
2. Техническое задание - это документ, который служит для описание того, что заказчик хочет получить в конечном виде. Техническое задание, как правило, прилагается к основному договору и включает полный перечень работ обязательного выполнения. 

 техническое задание состоит из:
◇ цель - задача, которую мы решим, реализуя данное техническое задание
◇ описание - изложение предстоящий разработок
◇ способ реализации - если вы не владеете терминами программиста, лучше всего описывать максимально свою задачу в цели и в описании, если вы владеете же знаниями, то пишите использование внешних библиотек (jquery, bootstrap) либо использование фреймворков (Angular, Vue, Ember, Laravel, YII и другие)
◇ оценка работы - один из самых важных пунктов, если вы не оценили стоимость работы, не пишите, потому как вы отфильтруете профессионалов и вполне вероятно получите не качественную работу. Посмотрите несколько предложений исполнителей, сравните цену. Цена не должна быть очень низкая, у исполнителя должен быть рейтинг и отзывы, если вы выберете самое дешевое предложение, вполне вероятно вы и получите такой результат.

3. Roadmap проекта — это графический обзор целей и результатов проекта, представленных на временной шкале. В отличие от плана проекта, где детали обрисованы, дорожная карта должна быть простой и не содержать мелочи.

=== этапа реализации

Минимально жизнеспособный продукт (minimum viable product, MVP) — продукт, обладающий минимальными, но достаточными для удовлетворения первых потребителей функциями. Основная задача — получение обратной связи для формирования гипотез дальнейшего развития продукта. Сбор информации от MVP зачастую дешевле, чем разработка продукта с большим количеством функций. Это позволяет снизить затраты и риски, если продукт не заработает, например, из-за неверных предположений

=== этапа тестирования

Тестирование программного обеспечения — процесс исследования, испытания программного продукта, имеющий своей целью проверку соответствия между реальным поведением программы и её ожидаемым поведением на конечном наборе тестов, выбранных определённым образом